version: "3.5"

networks:
  grafana:
  grafana-private:

volumes:
  grafana:
  influxdb:

secrets:
  grafana_admin_password:
    name: ${STACK_NAME:-technocore}_grafana_admin_password
    external: true

services:
  ingress:
    networks:
      - grafana

  grafana:
    deploy:
      labels:
        - com.ouroboros.enable=true
        - traefik.frontend.rule=$GRAFANA_ROUTING_LABEL
        - traefik.frontend.priority=$GRAFANA_ROUTING_LABEL_PRIORITY
        - traefik.port=3000
        - ${TRAEFIK_BASIC_AUTH}
        - ${TRAEFIK_BASIC_AUTH_REMOVE_HEADERS}
        - "traefik.frontend.auth.headerField=X-Traefik-basicauth"
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_grafana
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - INFLUXDB_USER=grafana
      - INFLUXDB_PASSWORD={{"{{DOCKER-SECRET:influxdb_password}}"}}
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD={{"{{DOCKER-SECRET:admin_password}}"}}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}/
      - GF_SERVER_DOMAIN=grafana.${DOMAIN}
      - GF_SMTP_ENABLED=${GF_SMTP_ENABLED:-true}
      - GF_SMTP_FROM_ADDRESS=${TECHNOCORE_SMTP_ADDRESS:-grafana@example.com}
      - GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME:-Grafana}
      - GF_SMTP_HOST=smtp_relay:587
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - DOMAIN=${DOMAIN:-}
    image: ${image_provider:-scififarms}/technocore-grafana:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - grafana
    secrets:
      - source: grafana_admin_password
        target: admin_password
    volumes:
      - grafana:/var/lib/grafana
      - ${DEV_MOUNT_GRAFANA_MIGRATIONS:-$EMPTY_MOUNT}
