version: "3.5"

networks:
  grafana:
  grafana-private:

volumes:
  grafana:
  influxdb:

secrets:
  grafana_influxdb_password:
    name: ${STACK_NAME:-technocore}_grafana_influxdb_password
    external: true
  grafana_admin_password:
    name: ${STACK_NAME:-technocore}_grafana_admin_password
    external: true
  influxdb_admin_password:
    name: ${STACK_NAME:-technocore}_influxdb_admin_password
    external: true
  influxdb_grafana_password:
    name: ${STACK_NAME:-technocore}_influxdb_grafana_password
    external: true

services:
  ingress:
    networks:
      - grafana

  grafana:
    deploy:
      labels:
        - com.ouroboros.enable=true
        - traefik.frontend.rule=$GRAFANA_ROUTING_LABEL
        - traefik.frontend.priority=$GRAFANA_ROUTING_LABEL_PRIORITY
        - traefik.port=3000
        - ${TRAEFIK_BASIC_AUTH}
        - ${TRAEFIK_BASIC_AUTH_REMOVE_HEADERS}
        - "traefik.frontend.auth.headerField=X-Traefik-basicauth"
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_grafana
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - INFLUXDB_USER=grafana
      - INFLUXDB_PASSWORD={{"{{DOCKER-SECRET:influxdb_password}}"}}
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD={{"{{DOCKER-SECRET:admin_password}}"}}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}/
      - GF_SERVER_DOMAIN=grafana.${DOMAIN}
      #- GF_SMTP_ENABLED=${GF_SMTP_ENABLED:-false}
      #- GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS:-grafana@test.com}
      #- GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME:-Grafana}
      #- GF_SMTP_HOST=${GF_SMTP_HOST:-smtp:25}
      #- GF_SMTP_USER=${GF_SMTP_USER}
      #- GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
    image: ${image_provider:-scififarms}/technocore-grafana:${TAG:-latest}
    #image: stefanprodan/swarmprom-grafana:5.3.4
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - grafana
      - grafana-private
    secrets:
      - source: grafana_influxdb_password
        target: influxdb_password
      - source: grafana_admin_password
        target: admin_password
    volumes:
      - grafana:/var/lib/grafana

  influxdb:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    environment:
      - INFLUXDB_ADMIN_USER=$ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD={{"{{DOCKER-SECRET:admin_password}}"}}
      - INFLUXDB_USER=home_assistant
      - INFLUXDB_USER_PASSWORD={{"{{DOCKER-SECRET:home_assistant_password}}"}}
      - INFLUXDB_READ_USER=grafana
      - INFLUXDB_READ_USER_PASSWORD={{"{{DOCKER-SECRET:grafana_password}}"}}
    image: ${image_provider:-scififarms}/technocore-influxdb:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - grafana-private
    secrets:
      - source: influxdb_admin_password
        target: admin_password
      - source: influxdb_grafana_password
        target: grafana_password
    volumes:
      - influxdb:/var/lib/influx