{
 "title": "Seedship Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Unavailable Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "entities",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "unavailable_entities" }
     ]
    }
   ]
  },
  {
   "title": "ESPs Down",
   "type": "graph",
   "description": "The number of uptime readings in 3 minutes. If it drops below 1, an ESP has stopped reporting.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "s",
     "query": "SELECT count(\"value\") FROM \"s\" WHERE (\"entity_id\" =~ /seedship/) AND $timeFilter GROUP BY time(3m), \"entity_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/seedship/" }
     ]
    }
   ]
  },
  {
   "title": "SeedShip PSI < 65 PSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" }
     ],
     "measurement": "PSI",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/(seedship|water_supply)/" }
     ]
    }
   ]
  },
  {
   "title": "Water System Bus PSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PSI",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/(water_supply_\\d+_bus)/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PSI",
     "query": "SELECT difference(first(\"value\")) FROM \"PSI\" WHERE (\"entity_id\" =~ /(water_supply_\\d+_bus)/) AND $timeFilter GROUP BY time(5m), \"entity_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/(water_supply_\\d+_bus)/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PSI",
     "query": "SELECT non_negative_derivative(mean(\"value\")) FROM \"PSI\" WHERE (\"entity_id\" =~ /(water_supply_\\d+_bus)/) AND $timeFilter GROUP BY time(5m), \"entity_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/(water_supply_\\d+_bus)/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PSI",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/(water_supply_\\d+_bus)/" }
     ]
    }
   ]
  },
  {
   "title": "PSI Standard Deviation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PSI",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PSI min (Last hour) > 75 PSI",
   "type": "graph",
   "description": "Checking for water intake. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PSI",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=~", "value": "/seedship_\\d+/" }
     ]
    }
   ]
  }
 ]
}